### ISSUE TITLE
Win32/Sabsik.FT.A!ml trojan detected by Microsoft Defender and Malwarebytes in the .zip file

### ISSUE THREAD

**Issue by HumanistAtypik** [officialnochill/WSA-QUICKINSTALL#2]
Win32/Sabsik.FT.A!ml trojan detected by Microsoft Defender and Malwarebytes in the .zip file

**Comment by officialnochill** [comment]
Flase flag, but I am going to private this since there are better alternatives now 

Take a look at wsa_pacman
